title: "Python para Análise de Dados: Fundamentos, Boas Práticas e Orientação a Objetos"
description: "Curso de Python para servidores do Ipea"
theme: jekyll-theme-cayman
# _config.yml
baseurl: "/python-ipea-fundamentos-objetos"  
url: "https://bafurtado.github.io"  

# Tema
theme: jekyll-theme-hacker

# Configurações do tema
show_downloads: false
github:
  is_project_page: false

# Plugins (seguros para GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Configurações de build
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Navegação - Páginas principais
header_pages:
  - README.md
  - configuracao/README.md
  - modulo1-fundamentos/README.md
  - modulo2-objetos/README.md
  - modulo3-projeto/README.md

# Informações do curso
author:
  name: "Bernardo Alves Furtado"
  email: "bernardo.furtado@ipea.gov.br"
  carga_horaria: "20 horas"
  modalidade: "Presencial"
  

# SEO
logo: "/images/logo_ENG_black.png"  # Opcional - se tiver
lang: "pt-BR"

# Personalização (opcional)
repository: "bafurtado/python-ipea-fundamentos-objetos" 

# Exclude arquivos desnecessários
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/